name: angular_node_bind
version: 0.1.3
author: Dart Authors <misc@dartlang.org>
description: Utilities to allow Angular templates to use Node.bind()
homepage: https://github.com/dart-lang/angular_node_bind
dependencies:
  angular: '>=0.9.2'
dev_dependencies:
  browser: '>=0.9.0'
  polymer_ui_elements: '>=0.1.1'
